security:
    # Hasheador de contraseñas
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Proveedor de usuarios (apunta a tu entidad Usuario)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall de Login: Pública, recibe email/pass y devuelve el Token JWT
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Firewall de la API: Protege todo lo que empiece por /api pidiendo el Token
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
      # Rutas públicas (No piden token)
      - { path: ^/api/login, roles: PUBLIC_ACCESS }
      - { path: ^/api/register, roles: PUBLIC_ACCESS }
      - { path: ^/api/productos$, methods: [ GET ], roles: PUBLIC_ACCESS }

      # Rutas de administración (Piden token y además ser ADMIN)
      - { path: ^/api/admin, roles: ROLE_ADMIN }

      # El resto de rutas /api (Piden token válido)
      - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

# Este bloque déjalo al final, optimiza el hasheo cuando hagas testing automático
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
