<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Producto extends \App\Entity\Producto implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'activo' => [parent::class, 'activo', null, 16],
        "\0".parent::class."\0".'categoria' => [parent::class, 'categoria', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'descripcion' => [parent::class, 'descripcion', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'imagenUrl' => [parent::class, 'imagenUrl', null, 16],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null, 16],
        "\0".parent::class."\0".'precio' => [parent::class, 'precio', null, 16],
        "\0".parent::class."\0".'precioOferta' => [parent::class, 'precioOferta', null, 16],
        "\0".parent::class."\0".'stock' => [parent::class, 'stock', null, 16],
        'activo' => [parent::class, 'activo', null, 16],
        'categoria' => [parent::class, 'categoria', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'descripcion' => [parent::class, 'descripcion', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'imagenUrl' => [parent::class, 'imagenUrl', null, 16],
        'nombre' => [parent::class, 'nombre', null, 16],
        'precio' => [parent::class, 'precio', null, 16],
        'precioOferta' => [parent::class, 'precioOferta', null, 16],
        'stock' => [parent::class, 'stock', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
