<?php

namespace ContainerRRxX7MF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminWebControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eUxJ3Ze.App\Controller\AdminWebController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eUxJ3Ze.App\\Controller\\AdminWebController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'producto' => ['privates', '.errored..service_locator.eUxJ3Ze.App\\Entity\\Producto', NULL, 'Cannot autowire service ".service_locator.eUxJ3Ze": it needs an instance of "App\\Entity\\Producto" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'producto' => 'App\\Entity\\Producto',
            'em' => '?',
        ]))->withContext('App\\Controller\\AdminWebController::delete()', $container);
    }
}
