<?php

namespace ContainerRRxX7MF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllergetStatsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3jxNKAp.App\Controller\AdminController::getStats()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3jxNKAp.App\\Controller\\AdminController::getStats()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pRepo' => ['privates', 'App\\Repository\\ProductoRepository', 'getProductoRepositoryService', true],
            'oRepo' => ['privates', 'App\\Repository\\PedidoRepository', 'getPedidoRepositoryService', true],
            'uRepo' => ['privates', 'App\\Repository\\UsuarioRepository', 'getUsuarioRepositoryService', true],
        ], [
            'pRepo' => 'App\\Repository\\ProductoRepository',
            'oRepo' => 'App\\Repository\\PedidoRepository',
            'uRepo' => 'App\\Repository\\UsuarioRepository',
        ]))->withContext('App\\Controller\\AdminController::getStats()', $container);
    }
}
