<?php

namespace ContainerRRxX7MF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminWebControllerdashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UmKm2LI.App\Controller\AdminWebController::dashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UmKm2LI.App\\Controller\\AdminWebController::dashboard()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'prodRepo' => ['privates', 'App\\Repository\\ProductoRepository', 'getProductoRepositoryService', true],
            'pedRepo' => ['privates', 'App\\Repository\\PedidoRepository', 'getPedidoRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UsuarioRepository', 'getUsuarioRepositoryService', true],
        ], [
            'prodRepo' => 'App\\Repository\\ProductoRepository',
            'pedRepo' => 'App\\Repository\\PedidoRepository',
            'userRepo' => 'App\\Repository\\UsuarioRepository',
        ]))->withContext('App\\Controller\\AdminWebController::dashboard()', $container);
    }
}
