<?php

namespace ContainerRRxX7MF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendarioControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rf_hB1y.App\Controller\CalendarioController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rf_hB1y.App\\Controller\\CalendarioController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\EventoCalendarioRepository', 'getEventoCalendarioRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'repo' => 'App\\Repository\\EventoCalendarioRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\CalendarioController::update()', $container);
    }
}
