<?php

namespace ContainerRRxX7MF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitCalendarioCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\InitCalendarioCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\InitCalendarioCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:init-calendario', [], 'Inicializa los 7 días de la semana en la tabla de EventoCalendario', false, #[\Closure(name: 'App\\Command\\InitCalendarioCommand')] fn (): \App\Command\InitCalendarioCommand => ($container->privates['App\\Command\\InitCalendarioCommand'] ?? $container->load('getInitCalendarioCommandService')));
    }
}
