<?php

namespace ContainerRRxX7MF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitCalendarioCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\InitCalendarioCommand' shared autowired service.
     *
     * @return \App\Command\InitCalendarioCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/InitCalendarioCommand.php';

        $container->privates['App\\Command\\InitCalendarioCommand'] = $instance = new \App\Command\InitCalendarioCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:init-calendario');
        $instance->setDescription('Inicializa los 7 días de la semana en la tabla de EventoCalendario');

        return $instance;
    }
}
