<?php

namespace ContainerRRxX7MF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HqKvLJh.App\Controller\MainController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HqKvLJh.App\\Controller\\MainController::index()'] = ($container->privates['.service_locator.HqKvLJh'] ?? $container->load('get_ServiceLocator_HqKvLJhService'))->withContext('App\\Controller\\MainController::index()', $container);
    }
}
