<?php

namespace ContainerRRxX7MF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductoControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dvWrUvX.App\Controller\ProductoController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dvWrUvX.App\\Controller\\ProductoController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'validator' => ['privates', 'validator', 'getValidatorService', false],
            'categoriaRepo' => ['privates', 'App\\Repository\\CategoriaRepository', 'getCategoriaRepositoryService', true],
        ], [
            'em' => '?',
            'validator' => '?',
            'categoriaRepo' => 'App\\Repository\\CategoriaRepository',
        ]))->withContext('App\\Controller\\ProductoController::create()', $container);
    }
}
