<?php

namespace ContainerRRxX7MF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductoControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LW3N1xz.App\Controller\ProductoController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LW3N1xz.App\\Controller\\ProductoController::index()'] = ($container->privates['.service_locator.LW3N1xz'] ?? $container->load('get_ServiceLocator_LW3N1xzService'))->withContext('App\\Controller\\ProductoController::index()', $container);
    }
}
