<?php

namespace ContainerRRxX7MF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductoControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._0.xEga.App\Controller\ProductoController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._0.xEga.App\\Controller\\ProductoController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\ProductoRepository', 'getProductoRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'categoriaRepo' => ['privates', 'App\\Repository\\CategoriaRepository', 'getCategoriaRepositoryService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', false],
        ], [
            'repo' => 'App\\Repository\\ProductoRepository',
            'em' => '?',
            'categoriaRepo' => 'App\\Repository\\CategoriaRepository',
            'validator' => '?',
        ]))->withContext('App\\Controller\\ProductoController::update()', $container);
    }
}
