<?php

namespace ContainerRRxX7MF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPedidoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0MHB.O9.App\Entity\Pedido' shared service.
     *
     * @return \App\Entity\Pedido
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0MHB.O9": it needs an instance of "App\\Entity\\Pedido" but this type has been excluded in "config/services.yaml".');
    }
}
