<?php

namespace ContainerRRxX7MF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPedidoControllercancelarService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0MHB.O9.App\Controller\PedidoController::cancelar()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0MHB.O9.App\\Controller\\PedidoController::cancelar()'] = ($container->privates['.service_locator.0MHB.O9'] ?? $container->load('get_ServiceLocator_0MHB_O9Service'))->withContext('App\\Controller\\PedidoController::cancelar()', $container);
    }
}
