<?php

namespace ContainerRRxX7MF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuarioControllertoggleEstadoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nsgrR7E.App\Controller\UsuarioController::toggleEstado()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nsgrR7E.App\\Controller\\UsuarioController::toggleEstado()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'usuario' => ['privates', '.errored..service_locator.nsgrR7E.App\\Entity\\Usuario', NULL, 'Cannot autowire service ".service_locator.nsgrR7E": it needs an instance of "App\\Entity\\Usuario" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'usuario' => 'App\\Entity\\Usuario',
            'em' => '?',
        ]))->withContext('App\\Controller\\UsuarioController::toggleEstado()', $container);
    }
}
