<?php

namespace ContainerRRxX7MF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuarioService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nsgrR7E.App\Entity\Usuario' shared service.
     *
     * @return \App\Entity\Usuario
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.nsgrR7E": it needs an instance of "App\\Entity\\Usuario" but this type has been excluded in "config/services.yaml".');
    }
}
