<?php

namespace ContainerRRxX7MF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuarioControllerlistarUsuariosService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ii.GJf6.App\Controller\UsuarioController::listarUsuarios()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ii.GJf6.App\\Controller\\UsuarioController::listarUsuarios()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'usuarioRepository' => ['privates', 'App\\Repository\\UsuarioRepository', 'getUsuarioRepositoryService', true],
        ], [
            'usuarioRepository' => 'App\\Repository\\UsuarioRepository',
        ]))->withContext('App\\Controller\\UsuarioController::listarUsuarios()', $container);
    }
}
